### ISSUE TITLE
moduleDirectories support

### ISSUE THREAD

**Issue by joelzimmer** [JoinColony/eslint-import-resolver-jest#3]
Any chance that [`moduleDirectories`](https://facebook.github.io/jest/docs/en/configuration.html#moduledirectories-array-string) could be supported as another path to resolve?

**Comment by chmanie** [comment]
Hey Joel,

I _think_ this should be possible. Let me take a crack at it.

**Comment by chmanie** [comment]
Hey again,

could you please install the branch `https://github.com/JoinColony/eslint-import-resolver-jest/tree/feature/3-module-directories` and see if it works in your use case?

**Comment by joelzimmer** [comment]
Will give it a shot in the morning! Thanks!

**Comment by joelzimmer** [comment]
@chmanie I wasn't able to directly install the branch, so forked it and linked it locally, but I wasn't able to get it working locally :/

**Comment by chmanie** [comment]
Hm, I guess then I might need some more information about your environment. What are you trying to accomplish exactly, what's your directory / module structure?

**Comment by chmanie** [comment]
@joelzimmer just checking back in. Could you solve this eventually?

**Comment by joelzimmer** [comment]
Hey @chmanie - I was able to work around this by adding it to my webpack resolve config

**Comment by chmanie** [comment]
OK then. I'll close this until it pops up again. Thanks for the feedback!

**Comment by ramiel** [comment]
Hello, I have this issue as well. I tried the branch feature/3-... but it's not working.
The reason why it's not working is that you check if the file exists but the extension is not appended to the modulePath
