### ISSUE TITLE
Wrong root directory is used when config file is passed in

### ISSUE THREAD

**Issue by tomprats** [JoinColony/eslint-import-resolver-jest#31]
# Problem

I'm running into a problem with how my Jest config and eslint config line up. If I disable the `import/no-unresolved` rule, my tests run file, Jest knows where imports are. If I add back the rule and remove `rootDir: "..",`, I get a validation error (seen below) from Jest. If I have both the rule and the `rootDir`, I get the rule error (seen below) from eslint.

The problem seems to be Jest expecting adjusting the root directory based on where the config file is placed, whereas this package adjusts the root directory based on where package.json is. I have a proposed solution after all the code/files.

## Errors

Validation Error:

```
● Validation Error:

  Module <rootDir>/test/support/test-helper.js in the setupFiles option was not found.
         <rootDir> is: /Users/tom/Desktop/development/repos/traitify/traitify-widgets/test

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html
```

Rule Error:

> 7:22  error  Unable to resolve path to module 'support/helpers'           import/no-unresolved

## Code

Running tests with `jest --config test/jest.config.js`

Folder structure: 

```
src/components/index.js
src/lib/index.js
test/.eslintrc
test/jest.config.js
test/components/index.test.js
test/lib/index.test.js
test/support/helpers.js
test/support/test-helper.js"
package.json
```

test/.eslintrc

```
{
  "extends": [
    "plugin:jest/recommended"
  ],
  "settings": {
    "import/resolver": {
      "jest": {
        "jestConfigFile": "./test/jest.config.js"
      },
      "webpack": {
        "config": "webpack.config.babel.js"
      }
    }
  }
}
```

test/jest.config.js

```
module.exports = {
  modulePaths: [
    "<rootDir>/src/",
    "<rootDir>/test/"
  ],
  rootDir: "..",
  setupFiles: [
    "<rootDir>/test/support/test-helper.js"
  ]
};
```

test/components/index.test.js

```
import "support/helper";

// Test stuff
```

# Solution

I looked into the code and the solution for my problems seems to be adding after `root = path.dirname(configFilePath)` after line 76. The only problem with the solution is that it breaks 5 tests. I'm not familiar enough with the code or tests to know whether or not it's just tests that are broken, or if actual use-cases will have problems too.

https://github.com/JoinColony/eslint-import-resolver-jest/blob/515b1d7b1299cc20155ced5450a948b956b124f1/src/index.js#L76

**Comment by tomprats** [comment]
Any chance someone could take a look at this? The problem is still alive and well

**Comment by rdig** [comment]
We're currently focusing our efforts in a different place right now, as we're pushing hard to have a feature shipped.

Unfortunately this means that packages such as this get less attention.

That being said, we would welcome a PR for this change.
