### ISSUE TITLE
modulePaths support

### ISSUE THREAD

**Issue by kentcdodds** [JoinColony/eslint-import-resolver-jest#4]
Thanks for this resolver!

Would you be interested in support for [`modulePaths`](https://facebook.github.io/jest/docs/en/configuration.html#modulepaths-array-string)?

**Comment by chmanie** [comment]
Sure! Want to submit a PR?

**Comment by kentcdodds** [comment]
Cool, yeah, I can look into it when I get the chance :)

**Comment by chmanie** [comment]
I tried to address this in v2.0.0. Hope it'll work for you!

**Comment by kentcdodds** [comment]
Fantastic! Thank you! This was just never high enough of a priority for me. I'll give this a look asap 🤘
